// flow-typed signature: 8ca2e35c3f35d05d53aba89ac1417d1e
// flow-typed version: <<STUB>>/git-head_v^1.20.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-head'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-head' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git-head/bin/git-head' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git-head/bin/git-head.js' {
  declare module.exports: $Exports<'git-head/bin/git-head'>;
}
declare module 'git-head/index' {
  declare module.exports: $Exports<'git-head'>;
}
declare module 'git-head/index.js' {
  declare module.exports: $Exports<'git-head'>;
}
