// flow-typed signature: 77cc1e030e223f097336bcceeeb68b85
// flow-typed version: <<STUB>>/parse-github-repo-url_v^1.4.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-github-repo-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-github-repo-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'parse-github-repo-url/index' {
  declare module.exports: $Exports<'parse-github-repo-url'>;
}
declare module 'parse-github-repo-url/index.js' {
  declare module.exports: $Exports<'parse-github-repo-url'>;
}
