// flow-typed signature: 92d98d100e4a711fde5d4d9b9d1f5749
// flow-typed version: <<STUB>>/github_v11.0.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'github'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'github' {
  declare class Github {
    constructor (
        options: {
        port: string,
        protocol: ?string,
        host: string,
        pathPrefix: ?string,
      }
    ): Github;

    gitdata: {
      createReference: (
        tag: {
          owner: string,
          repo: string,
          ref: string,
          sha: string,
        },
      ) => Promise<any>
    };

    repos: {
      createRelease: (
        release: {
          owner: string,
          repo: string,
          tag_name: string,
          name: string,
          body: string,
          target_committish: string,
          draft: boolean,
        },
      ) => Promise<any>
    };

    authenticate (
      options: {
        type: string,
        token: string,
      }
    ): void;
  }

  declare export default Github
}
