// flow-typed signature: baafef899512547bf01b99b3e75f0da9
// flow-typed version: <<STUB>>/parse-github-repo-url_v1.4.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-github-repo-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-github-repo-url' {
  declare module.exports: (url: string) => ?Array<string>;
}
