// @flow
// flow-typed signature: 538d99216abd99b336919c191fee6d5e
// flow-typed version: <<STUB>>/shelljs_v^0.7.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shelljs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shelljs' {
  declare module.exports: {
    exec: ((
      cmd: string,
      options: Object,
      cb: (
        code: number,
        stdout: string,
        stderr: string,
      ) => void,
    ) => void) & (
      cmd: string,
      options: Object,
    ) => {
      code: number,
      stderr: string,
      stdout: string,
    }
  }
}
