// flow-typed signature: 018da7198ca2bb9bd05ea717d645f596
// flow-typed version: <<STUB>>/version-to-commit_v^1.1.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'version-to-commit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'version-to-commit' {
  declare module.exports: (
    packageName: string,
    version: string,
    callback: (
      err: Error,
      commit: string
    ) => void
  ) => void
}
