// flow-typed signature: 3144c0eabafa6c0e7fdbe4200fbaa5c5
// flow-typed version: <<STUB>>/@semantic-release/commit-analyzer_v^3.0.6/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@semantic-release/commit-analyzer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@semantic-release/commit-analyzer' {
  declare module.exports: (
    pluginConfig: Object,
    config: Object,
    done: Function,
  ) => void;
}
