// flow-typed signature: dd8eb5083cb843155cb767a239d4356b
// flow-typed version: <<STUB>>/@team-griffin/eslint-config_v^3.0.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@team-griffin/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@team-griffin/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@team-griffin/eslint-config/frontend-config/core' {
  declare module.exports: any;
}

declare module '@team-griffin/eslint-config/frontend-config/flowtype' {
  declare module.exports: any;
}

declare module '@team-griffin/eslint-config/frontend-config/fp' {
  declare module.exports: any;
}

declare module '@team-griffin/eslint-config/frontend-config/import' {
  declare module.exports: any;
}

declare module '@team-griffin/eslint-config/frontend-config/index' {
  declare module.exports: any;
}

declare module '@team-griffin/eslint-config/frontend-config/jsx-a11y' {
  declare module.exports: any;
}

declare module '@team-griffin/eslint-config/frontend-config/react' {
  declare module.exports: any;
}

declare module '@team-griffin/eslint-config/frontend-testing-config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@team-griffin/eslint-config/frontend-config/core.js' {
  declare module.exports: $Exports<'@team-griffin/eslint-config/frontend-config/core'>;
}
declare module '@team-griffin/eslint-config/frontend-config/flowtype.js' {
  declare module.exports: $Exports<'@team-griffin/eslint-config/frontend-config/flowtype'>;
}
declare module '@team-griffin/eslint-config/frontend-config/fp.js' {
  declare module.exports: $Exports<'@team-griffin/eslint-config/frontend-config/fp'>;
}
declare module '@team-griffin/eslint-config/frontend-config/import.js' {
  declare module.exports: $Exports<'@team-griffin/eslint-config/frontend-config/import'>;
}
declare module '@team-griffin/eslint-config/frontend-config/index.js' {
  declare module.exports: $Exports<'@team-griffin/eslint-config/frontend-config/index'>;
}
declare module '@team-griffin/eslint-config/frontend-config/jsx-a11y.js' {
  declare module.exports: $Exports<'@team-griffin/eslint-config/frontend-config/jsx-a11y'>;
}
declare module '@team-griffin/eslint-config/frontend-config/react.js' {
  declare module.exports: $Exports<'@team-griffin/eslint-config/frontend-config/react'>;
}
declare module '@team-griffin/eslint-config/frontend-testing-config.js' {
  declare module.exports: $Exports<'@team-griffin/eslint-config/frontend-testing-config'>;
}
